FIND_PATH(XXHash_INCLUDE_DIR NAMES xxhash.h)
FIND_LIBRARY(XXHash_LIBRARY NAMES xxhash)


INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(XXHash DEFAULT_MSG XXHash_LIBRARY XXHash_INCLUDE_DIR)

set(XXHash_INCLUDE_DIRS "${XXHash_INCLUDE_DIR}")
set(XXHash_LIBRARIES "${XXHash_LIBRARY}")