FIND_LIBRARY(GMP_LIBRARY NAMES gmp)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GMP DEFAULT_MSG GMP_LIBRARY )

IF(GMP_FOUND)
	SET(GMP_LIBRARIES ${GMP_LIBRARY})
ELSE(QUADMATH_FOUND)
	SET(GMP_LIBRARIES)
ENDIF(GMP_FOUND)