FIND_PATH(LIBZ3_INCLUDE_DIR NAMES z3.h)
FIND_LIBRARY(LIBZ3_LIBRARY NAMES z3)


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBZ3 DEFAULT_MSG LIBZ3_LIBRARY LIBZ3_INCLUDE_DIR)

IF(LIBZ3_FOUND)
	SET(Z3_LIBRARIES ${LIBZ3_LIBRARY} )
	SET(Z3_INCLUDE_DIRS ${LIBZ3_INCLUDE_DIR})
ELSE(LIBZ3_FOUND)
	SET(Z3_LIBRARIES)
	SET(Z3_INCLUDE_DIRS)
ENDIF(LIBZ3_FOUND)