FIND_LIBRARY(QUADMATH_LIBRARY NAMES quadmath)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QUADMATH DEFAULT_MSG QUADMATH_LIBRARY )

IF(QUADMATH_FOUND)
	SET(QUADMATH_LIBRARIES ${QUADMATH_LIBRARY})
ELSE(QUADMATH_FOUND)
	SET(QUADMATH_LIBRARIES)
ENDIF(QUADMATH_FOUND)