FIND_PATH(GRAPHVIZ_INCLUDE_DIR NAMES "graphviz/cgraph.h")
FIND_LIBRARY(GRAPHVIZ_LIBRARY NAMES cgraph)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CGraph DEFAULT_MSG GRAPHVIZ_LIBRARY GRAPHVIZ_INCLUDE_DIR)

IF(CGraph_FOUND)
	SET(CGRAPH_LIBRARIES ${GRAPHVIZ_LIBRARY})
	SET(CGRAPH_INCLUDE_DIRS ${GRAPHVIZ_INCLUDE_DIR})
ELSE(CGraph_FOUND)
	SET(CGRAPH_LIBRARIES)
	SET(CGRAPH_INCLUDE_DIRS)
ENDIF(CGraph_FOUND)