include(GNUInstallDirs)


# when building, don't use the install RPATH already
# (but later on when installing)

SET(CPACK_GENERATOR "ZIP")
set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}-${GIT_HASH}")





if (ENABLE_SYMBOLIC)
   INSTALL (TARGETS  smtlib DESTINATION  ${CMAKE_INSTALL_LIBDIR})  
endif(ENABLE_SYMBOLIC)

if (ENABLE_PYTHON)
     find_package (Python3 REQUIRED)
     if (NOT CMAKE_INSTALL_PYTHON_LIBDIR)
      set(CMAKE_INSTALL_PYTHON_LIBDIR "${CMAKE_INSTALL_LIBDIR}/python${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR}/site-packages")
      endif ()
      set_target_properties(pyminimc
                           PROPERTIES INSTALL_RPATH "$ORIGIN:$ORIGIN/../../.."
      			   )

      INSTALL (TARGETS pyminimc
               COMPONENT PYTHON  
	       DESTINATION ${CMAKE_INSTALL_PYTHON_LIBDIR}/minimc)
      INSTALL(DIRECTORY ${PROJECT_SOURCE_DIR}/python/minimc/ DESTINATION ${CMAKE_INSTALL_PYTHON_LIBDIR}/minimc)
endif(ENABLE_PYTHON)



include(CPack)	
