name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine
    steps:
    - uses: actions/checkout@v2
    - name: BuildDep
      run:  apk update && apk add python3 py3-pip cmake g++ make llvm18-dev llvm18-static llvm18-gtest git flex bison boost-dev py3-jinja2 py3-yaml xxhash-dev
    - name: Setup
      run: mkdir build && cd build && cmake  -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cd build && make
    - name: package
      run: cd build && make package
    - uses: actions/upload-artifact@v2
      with:
        name: build 
        path: build/*.zip 
